name: BrownLikeBears composer

on:
  push:
    branches:
      - master
    paths:
      - 'gfx/BrownLikeBears/**'
      - '.github/workflows/blb_ci_build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gfx/BrownLikeBears/**'
      - '.github/workflows/blb_ci_build.yml'

jobs:
  build:
    uses: ./.github/workflows/composer_template.yml
    with:
      tileset: BrownLikeBears
      composer-args: --use-all --obsolete-fillers
