name: Mushroom-Dream composer

on:
  push:
    branches:
      - master
    paths:
      - 'gfx/Mushroom-Dream/**'
      - '.github/workflows/MD_ci_build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gfx/Mushroom-Dream/**'
      - '.github/workflows/MD_ci_build.yml'

jobs:
  build:
    uses: ./.github/workflows/composer_template.yml
    with:
      tileset: Mushroom-Dream
      composer-args: --use-all --obsolete-fillers
