name: MShockXotto+ composer

on:
  push:
    branches:
      - master
    paths:
      - 'gfx/MShockXotto\+/**'
      - '.github/workflows/msx_ci_build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gfx/MShockXotto\+/**'
      - '.github/workflows/msx_ci_build.yml'

jobs:
  build:
    uses: ./.github/workflows/composer_template.yml
    with:
      tileset: MShockXotto+
      composer-args: --use-all
