name: NeoDays composer

on:
  push:
    branches:
      - master
    paths:
      - 'gfx/NeoDays/**'
      - '.github/workflows/Neodays_ci_build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gfx/NeoDays/**'
      - '.github/workflows/Neodays_ci_build.yml'

jobs:
  build:
    uses: ./.github/workflows/composer_template.yml
    with:
      tileset: NeoDays
      composer-args: --use-all
