# preforms CI builds using compose.py from
# https://github.com/CleverRaven/Cataclysm-DDA
#
# This action is triggered by any PR against the master branch as well
# as on any push to the master branch itself
# that changes any file in gfx/UltimateCataclysm folder
name: UltimateCataclysm composer

on:
  push:
    branches:
      - master
    paths:
      - 'gfx/UltimateCataclysm/**'
      - '.github/workflows/Ultica_ci_build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gfx/UltimateCataclysm/**'
      - '.github/workflows/Ultica_ci_build.yml'

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  call-reusable-builder:
    uses: ./.github/workflows/reusable-builder.yml@${{ github.head_ref }}
    with:
      tileset: UltimateCataclysm
      compose_args: --use-all --obsolete-fillers
