# preforms CI builds using compose.py from
# https://github.com/CleverRaven/Cataclysm-DDA
#
# This action is triggerd by any PR against the master branch as well
# as on any push to the master branch itself
# that changes any file in gfx/UltimateCataclysm folder
name: UltimateCataclysm composer

on:
  push:
    branches:
      - master
    paths:
      - 'gfx/UltimateCataclysm/**'
      - '.github/workflows/Ultica_ci_build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gfx/UltimateCataclysm/**'
      - '.github/workflows/Ultica_ci_build.yml'

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies and set env vars
        run: |
          sudo apt install musl-dev gcc libvips-dev python3-dev python3-pip python3-wheel
          pip3 install pyvips

          echo "tileset=UltimateCataclysm" >> $GITHUB_ENV
          echo "compose_args=--use-all --obsolete-fillers" >> $GITHUB_ENV
          echo "build_dir=build" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        id: build
        run: |
          mkdir "${{ env.build_dir }}"
          wget -q -P "${{ env.build_dir }}" https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/compose.py \
          || echo "Error: Failed to get compose.py"

          python3 "${{ env.build_dir }}/compose.py" ${{ env.compose_args }} "gfx/${{ env.tileset }}" "${{ env.build_dir }}"
          [ -f "gfx/${{ env.tileset }}/fallback.png" ] && cp "gfx/${{ env.tileset }}/fallback.png" "${{ env.build_dir }}/"

          artifact_name="${{ env.tileset }}-${GITHUB_SHA::7}"

          mkdir "$artifact_name"
          mv "${{{ env.build_dir }}}"/*.png           "$artifact_name"
          cp "${{ env.build_dir }}/tile_config.json"  "$artifact_name"
          cp "gfx/${{ env.tileset }}/tileset.txt"     "$artifact_name"
          cp "gfx/${{ env.tileset }}/layering.json"   "$artifact_name"

          echo ::set-output name=artifact_name::"$artifact_name"

      - name: Compare IDs
        id: compare
        run: |
          if [[ -n "${{ github.base_ref }}" ]]; then  # github.base_ref is only set for PRs

            echo "Switching to the target branch to get differences between ID lists"
            git fetch --depth=1 origin +${{ github.base_ref }}
            git checkout origin/${{ github.base_ref }}
            mkdir "${{ env.build_dir }}/base_json/"
            python3 "${{ env.build_dir }}/compose.py" ${{ env.compose_args }} --only-json "gfx/${{ env.tileset }}" "${{ env.build_dir }}/base_json/"
            wget -q -P "${{ env.build_dir }}" https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/list_tileset_ids.py \
            || echo "Error: Failed to get list_tileset_ids.py"
            echo -e "\nDifferences in IDs:"
            (diff -u0 <(python3 "${{ env.build_dir }}/list_tileset_ids.py" "${{ env.build_dir }}/base_json/") <(python3 "${{ env.build_dir }}/list_tileset_ids.py" "${{ env.build_dir }}/")) | tail -n +3

          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ${{ steps.build.outputs.artifact_name }}
